spring:
  application:
    name: cherry-dev

  datasource:
    url: jdbc:mysql://mysql:3306/cherry
    username: myuser
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        order_inserts: true
        format_sql: true

cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET, POST, PUT, DELETE, OPTIONS, HEAD
  allowed-headers: "*"

kakao:
  client_id: ${KAKAO_CLIENT_ID}
  redirect_uri: ${KAKAO_REDIRECT_URL}