spring:
  application:
    name: cherry
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        order_inserts: true
        format_sql: true

  docker:
    compose:
      lifecycle-management: start_only

cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET, POST, PUT, DELETE
  allowed-headers: Access-Control-Allow-Origin, Content-type, Access-Control-Allow-Headers, Authorization, X-Requested-With

kakao:
  client_id: ${KAKAO_CLIENT_ID}
  redirect_uri: ${KAKAO_REDIRECT_URL}