spring:
  application:
    name: cherry-local

  config:
    import:
      - optional:file:.env[.properties]

  docker:
    compose:
      lifecycle-management: start_only

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        order_inserts: true
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  cloud:
    aws:
      credentials:
        access-key: ${AWS_S3_ACCESS_KEY}
        secret-key: ${AWS_S3_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: cherry-dev-assets
        allowed-mime-types: image/jpeg,image/jpg,image/png,image/gif
      stack:
        auto: false

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-seconds: ${ACCESS_TOKEN_EXPIRATION_SECONDS}
  refresh-token-expiration-seconds: ${REFRESH_TOKEN_EXPIRATION_SECONDS}
  temp-token-expiration-seconds: ${TEMP_TOKEN_EXPIRATION_SECONDS}

cookie:
  domain: localhost

cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET, POST, PUT, DELETE, OPTIONS, HEAD
  allowed-headers: "*"

kakao:
  client_id: ${KAKAO_CLIENT_ID}
  redirect_uri: ${KAKAO_REDIRECT_URL}

